version: '3.3'
services:
  nemid-api:
    build:
      context: "./nemid-api"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - CONTAINERIZED=true
    volumes:
      - ./db:/db

  nemid-auth:
    build:
      context: "./nemid-auth"
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - CONTAINERIZED=true
      - API_STRING=http://nemid-api:3000
    volumes:
      - ./db:/db

  nemid-tokengen:
    build:
      context: "./nemid-tokengen"
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - CONTAINERIZED=true
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_SECRET_TYPE=${JWT_SECRET_TYPE}
    volumes:
      - ./db:/db