version: '3.3'
services:
  nemid-api:
    build:
      context: "./nemid-api"
    ports:
      - "$PORT_NEMID_API:$PORT_NEMID_API"
    environment:
      - PORT=$PORT_NEMID_API
      - CONTAINERIZED=true
    volumes:
      - ./db:/db

  nemid-auth:
    build:
      context: "./nemid-auth"
    ports:
      - "$PORT_NEMID_AUTH:$PORT_NEMID_AUTH"
    environment:
      - PORT=$PORT_NEMID_AUTH
      - CONTAINERIZED=true
      - API_STRING=http://nemid-api:$PORT_NEMID_API
    volumes:
      - ./db:/db

  nemid-tokengen:
    build:
      context: "./nemid-tokengen"
    ports:
      - "$PORT_NEMID_TOKENGEN:$PORT_NEMID_TOKENGEN"
    environment:
      - PORT=$PORT_NEMID_TOKENGEN
      - CONTAINERIZED=true
      - JWT_SECRET_KEY=$JWT_SECRET_KEY
      - JWT_SECRET_TYPE=$JWT_SECRET_TYPE
    volumes:
      - ./db:/db

  nemid-gateway:
    build:
      context: "./nemid-gateway"
    ports:
      - "$PORT_NEMID_GATEWAY:$PORT_NEMID_GATEWAY"
    environment:
      - PORT=$PORT_NEMID_GATEWAY
      - CONTAINERIZED=true
      - NEMID_API_STRING=http://nemid-api:$PORT_NEMID_API
      - NEMID_AUTH_STRING=http://nemid-auth:$PORT_NEMID_AUTH
      - NEMID_TOKENGEN_STRING=http://nemid-tokengen:$PORT_NEMID_TOKENGEN

  main-system:
    build:
      context: "./main-system"
    ports:
      - "$PORT_MAIN_SYSTEM:$PORT_MAIN_SYSTEM"
    environment:
      - PORT=$PORT_MAIN_SYSTEM
      - CONTAINERIZED=true
      - AUTH_STRING=http://nemid-auth:$PORT_NEMID_AUTH
      - API_STRING=http://nemid-api:$PORT_NEMID_API
    volumes:
      - ./db:/db